'use client';

import { useState, useEffect } from 'react';
import { Card } from '@/shared/ui/card';
import { Textarea } from '@/shared/ui/textarea';
import { Button } from '@/shared/ui/button';
import { Badge } from '@/shared/ui/badge';
import { ToolLayout, ToolSection } from '@/shared/ui/tool-layout';
import { analyzeCode } from './lib/parser';
import { AnalysisResult, Language } from './lib/types';
import { config } from './tool.config';
import { FileCode2, Zap, Info, Sparkles, Copy, Check } from 'lucide-react';
import { useCopyToClipboard } from '@/shared/lib/hooks/use-copy-to-clipboard';
import { SeoGuide } from './ui/seo-guide';

const LANG_CONFIG: Record<Language, { color: string; label: string }> = {
  javascript: { color: 'bg-yellow-100 text-yellow-800 border-yellow-200', label: 'JavaScript' },
  typescript: { color: 'bg-blue-100 text-blue-800 border-blue-200', label: 'TypeScript' },
  html: { color: 'bg-orange-100 text-orange-800 border-orange-200', label: 'HTML' },
  css: { color: 'bg-sky-100 text-sky-800 border-sky-200', label: 'CSS' },
  json: { color: 'bg-gray-100 text-gray-800 border-gray-200', label: 'JSON' },
  sql: { color: 'bg-purple-100 text-purple-800 border-purple-200', label: 'SQL' },
  markdown: { color: 'bg-emerald-100 text-emerald-800 border-emerald-200', label: 'Markdown' },
  yaml: { color: 'bg-rose-100 text-rose-800 border-rose-200', label: 'YAML' },
  graphql: { color: 'bg-pink-100 text-pink-800 border-pink-200', label: 'GraphQL' },
  unknown: { color: 'bg-zinc-100 text-zinc-800 border-zinc-200', label: 'Unknown' },
};

export default function CodeLensTool() {
  const [code, setCode] = useState(`<section className="mt-8 p-6 bg-blue-50 dark:bg-blue-950 rounded-lg">
  <h3 className="text-lg font-semibold mb-3">함께 사용하면 좋은 도구</h3>
</section>`);
  
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const { status, copyToClipboard } = useCopyToClipboard({ resetDelay: 2000 });

  useEffect(() => {
    if (!code.trim()) {
      setResult(null);
      return;
    }
    const analysis = analyzeCode(code);
    setResult(analysis);
  }, [code]);

  const handleCopyReport = async () => {
    if (!result) return;
    const plainSections = result.sections.map(s => 
      `[${s.title}]\n${s.content.map(c => `• ${c.replace(/<[^>]*>?/gm, '')}`).join('\n')}`
    ).join('\n\n');
    const fullReport = `${result.title}\n\n${plainSections}\n\n(Generated by Code Lens)`;
    await copyToClipboard(fullReport);
  };

  return (
    <ToolLayout config={config}>
      <ToolSection title="코드 렌즈 (Code Lens)" description="코드를 붙여넣으면 분석 엔진이 코드의 의도와 구조를 친절하게 설명해줍니다.">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-[700px]">
          <div className="flex flex-col h-full space-y-2 overflow-hidden">
            <div className="flex justify-between items-center">
              <label className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <FileCode2 className="w-4 h-4" /> 소스 코드 입력
              </label>
              <div className="flex flex-wrap gap-2 justify-end">
                <Button variant="ghost" size="sm" onClick={() => setCode('SELECT * FROM users JOIN orders ON users.id = orders.user_id WHERE users.active = true;')} className="text-[10px] h-6 px-2">SQL</Button>
                <Button variant="ghost" size="sm" onClick={() => setCode('{\"name\": \"vlog\", \"version\": \"1.0.0\"}')} className="text-[10px] h-6 px-2">JSON</Button>
                <Button variant="ghost" size="sm" onClick={() => setCode('')} className="text-[10px] h-6 px-2 text-destructive">지우기</Button>
              </div>
            </div>
            <div className="flex-1 border-2 rounded-xl bg-muted/30 focus-within:border-primary transition-colors overflow-hidden flex flex-col">
              <Textarea
                className="flex-1 font-mono text-sm resize-none bg-transparent p-4 leading-relaxed border-none focus-visible:ring-0 overflow-y-auto"
                placeholder="여기에 코드를 붙여넣으세요..."
                value={code}
                onChange={(e) => setCode(e.target.value)}
                spellCheck={false}
              />
            </div>
          </div>

          <div className="flex flex-col h-full space-y-4 overflow-hidden">
            <div className="flex items-center justify-between">
               <label className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <Zap className="w-4 h-4 text-amber-500" /> 코드 상세 분석 리포트
              </label>
              {result && (
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={handleCopyReport} className="h-7 text-xs gap-1.5">
                    {status === 'copied' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} 리포트 복사
                  </Button>
                  <Badge variant="outline" className={`${LANG_CONFIG[result.language].color}`}>
                    {LANG_CONFIG[result.language].label}
                  </Badge>
                </div>
              )}
            </div>

            <Card className="flex-1 p-0 border-2 border-primary/10 bg-card overflow-hidden flex flex-col">
              {!result ? (
                <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground space-y-4">
                  <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center">
                    <Sparkles className="w-8 h-8 opacity-20" />
                  </div>
                  <p>코드를 입력하면 상세한 해설이 나타납니다.</p>
                </div>
              ) : (
                <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar text-left">
                  <div className="bg-primary/5 border border-primary/20 p-4 rounded-xl">
                    <p className="text-lg font-bold text-primary leading-tight">{result.title}</p>
                  </div>
                  {result.sections.map((section, idx) => (
                    <div key={idx} className="space-y-3">
                      <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b pb-2">{section.title}</h3>
                      <ul className="space-y-3">
                        {section.content.map((item, cIdx) => (
                          <li key={cIdx} className="text-sm leading-relaxed text-muted-foreground flex gap-2 text-left">
                            <span className="text-primary font-bold mt-0.5">•</span>
                            <span dangerouslySetInnerHTML={{ __html: item.replace(/\*\*(.*?)\*\*/g, '<strong class="text-foreground">$1</strong>') }} />
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </div>
        </div>
      </ToolSection>

      <div className="my-12" />
      <SeoGuide />
    </ToolLayout>
  );
}
