'use client';

import { useState, useEffect } from 'react';
import { Card } from '@/shared/ui/card';
import { Textarea } from '@/shared/ui/textarea';
import { Button } from '@/shared/ui/button';
import { Badge } from '@/shared/ui/badge';
import { ToolLayout, ToolSection } from '@/shared/ui/tool-layout';
import { analyzeCode } from './lib/parser';
import { AnalysisResult, Language } from './lib/types';
import { config } from './tool.config';
import { FileCode2, Zap, Info, Sparkles, Copy, Check } from 'lucide-react';
import { useCopyToClipboard } from '@/shared/lib/hooks/use-copy-to-clipboard';

const LANG_CONFIG: Record<Language, { color: string; label: string }> = {
  javascript: { color: 'bg-yellow-100 text-yellow-800 border-yellow-200', label: 'JavaScript' },
  typescript: { color: 'bg-blue-100 text-blue-800 border-blue-200', label: 'TypeScript' },
  html: { color: 'bg-orange-100 text-orange-800 border-orange-200', label: 'HTML' },
  css: { color: 'bg-sky-100 text-sky-800 border-sky-200', label: 'CSS' },
  json: { color: 'bg-gray-100 text-gray-800 border-gray-200', label: 'JSON' },
  sql: { color: 'bg-purple-100 text-purple-800 border-purple-200', label: 'SQL' },
  markdown: { color: 'bg-emerald-100 text-emerald-800 border-emerald-200', label: 'Markdown' },
  yaml: { color: 'bg-rose-100 text-rose-800 border-rose-200', label: 'YAML' },
  graphql: { color: 'bg-pink-100 text-pink-800 border-pink-200', label: 'GraphQL' },
  unknown: { color: 'bg-zinc-100 text-zinc-800 border-zinc-200', label: 'Unknown' },
};

export default function CodeLensTool() {
  const [code, setCode] = useState(`<section className="mt-8 p-6 bg-blue-50 dark:bg-blue-950 rounded-lg">
  <h3 className="text-lg font-semibold mb-3">함께 사용하면 좋은 도구</h3>
  <p className="text-gray-700 dark:text-gray-300 mb-3">
    코드 작업을 더 효율적으로 만들어줄 다른 도구들도 확인해보세요.
  </p>
  <div className="flex flex-wrap gap-3">
    <a href="/utility/visualizer" className="text-blue-600 hover:underline font-bold">
      → Tailwind CSS 클래스 시각화기
    </a>
  </div>
</section>`);
  
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const { status, copyToClipboard } = useCopyToClipboard({ resetDelay: 2000 });

  useEffect(() => {
    if (!code.trim()) {
      setResult(null);
      return;
    }
    const analysis = analyzeCode(code);
    setResult(analysis);
  }, [code]);

  const handleCopyReport = async () => {
    if (!result) return;
    
    const plainSections = result.sections.map(s => 
      `[${s.title}]\n${s.content.map(c => `• ${c.replace(/<[^>]*>?/gm, '')}`).join('\n')}`
    ).join('\n\n');
    
    const fullReport = `${result.title}\n\n${plainSections}\n\n(Generated by Code Lens)`;
    await copyToClipboard(fullReport);
  };

  return (
    <ToolLayout config={config}>
      <ToolSection title="코드 렌즈 (Code Lens)" description="코드를 붙여넣으면 분석 엔진이 코드의 의도와 구조를 친절하게 설명해줍니다.">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-[700px]">
          {/* 입력창: 내부 스크롤 보장 */}
          <div className="flex flex-col h-full space-y-2 overflow-hidden">
            <div className="flex justify-between items-center">
              <label className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <FileCode2 className="w-4 h-4" />
                소스 코드 입력
              </label>
              <div className="flex flex-wrap gap-2 justify-end">
                <Button variant="ghost" size="sm" onClick={() => setCode('SELECT * FROM users JOIN orders ON users.id = orders.user_id WHERE users.active = true;')} className="text-[10px] h-6 px-2">SQL</Button>
                <Button variant="ghost" size="sm" onClick={() => setCode(`{
  "name": "vlog-project",
  "version": "1.0.0",
  "dependencies": {
    "next": "16.0.10",
    "react": "19.0.0"
  }
}`)} className="text-[10px] h-6 px-2">JSON</Button>
                <Button variant="ghost" size="sm" onClick={() => setCode('# 프로젝트 가이드\n\n이 도구는 **AI 없이** 작동합니다.\n\n- [홈으로](/) 이동\n- [도구 목록](/tools) 확인')} className="text-[10px] h-6 px-2">MD</Button>
                <Button variant="ghost" size="sm" onClick={() => setCode('on: [push]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3')} className="text-[10px] h-6 px-2">YAML</Button>
                <Button variant="ghost" size="sm" onClick={() => setCode('')} className="text-[10px] h-6 px-2 text-destructive">지우기</Button>
              </div>
            </div>
            <div className="flex-1 border-2 rounded-xl bg-muted/30 focus-within:border-primary transition-colors overflow-hidden flex flex-col">
              <Textarea
                className="flex-1 font-mono text-sm resize-none bg-transparent p-4 leading-relaxed border-none focus-visible:ring-0 overflow-y-auto"
                placeholder="여기에 코드를 붙여넣으세요..."
                value={code}
                onChange={(e) => setCode(e.target.value)}
                spellCheck={false}
              />
            </div>
          </div>

          {/* 결과창: 내부 스크롤 보장 */}
          <div className="flex flex-col h-full space-y-4 overflow-hidden">
            <div className="flex items-center justify-between">
               <label className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <Zap className="w-4 h-4 text-amber-500" />
                코드 상세 분석 리포트
              </label>
              <div className="flex items-center gap-2">
                {result && (
                  <>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={handleCopyReport}
                      className="h-7 text-xs gap-1.5"
                    >
                      {status === 'copied' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                      리포트 복사
                    </Button>
                    <Badge variant="outline" className={`${LANG_CONFIG[result.language].color}`}>
                      {LANG_CONFIG[result.language].label}
                    </Badge>
                  </>
                )}
              </div>
            </div>

            <Card className="flex-1 p-0 border-2 border-primary/10 bg-card overflow-hidden flex flex-col">
              {!result ? (
                <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground space-y-4">
                  <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center">
                    <Sparkles className="w-8 h-8 opacity-20" />
                  </div>
                  <p>코드를 입력하면 상세한 해설이 나타납니다.</p>
                </div>
              ) : (
                <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
                  {/* 메인 한 줄 요약 */}
                  <div className="bg-primary/5 border border-primary/20 p-4 rounded-xl">
                    <p className="text-lg font-bold text-primary leading-tight">
                      {result.title}
                    </p>
                  </div>

                  {/* 상세 섹션들 */}
                  {result.sections.map((section, idx) => (
                    <div key={idx} className="space-y-3">
                      <h3 className="text-sm font-bold text-foreground flex items-center gap-2 border-b pb-2">
                        {section.title}
                      </h3>
                      <ul className="space-y-3">
                        {section.content.map((item, cIdx) => (
                          <li key={cIdx} className="text-sm leading-relaxed text-muted-foreground flex gap-2">
                            <span className="text-primary font-bold mt-0.5">•</span>
                            <span dangerouslySetInnerHTML={{ 
                                __html: item.replace(/\*\*(.*?)\*\*/g, '<strong class="text-foreground">$1</strong>') 
                            }} />
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}

                  {/* 키워드 태그 */}
                  <div className="pt-4">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mb-3 flex items-center gap-1">
                      <Info className="w-3 h-3" />
                      Detected Elements
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {result.keywords.map((word, idx) => (
                        <Badge key={idx} variant="secondary" className="text-[10px] px-2 py-0 capitalize">
                          {word}
                        </Badge>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </Card>
          </div>
        </div>
      </ToolSection>

      <div className="my-12 border-t pt-12" />

      <ToolSection title="사용 가이드" headingLevel="h2" className="my-8">
        <p className="mb-6 text-muted-foreground">
          '코드 렌즈'는 복잡한 소스 코드를 읽기 쉽게 풀어 설명해주는 코드 해설 도구입니다. 동료의 코드를 검토하거나 오픈소스의 동작 원리를 파악할 때 유용합니다.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-4 rounded-lg border bg-muted/20">
            <h4 className="font-bold mb-2 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs">1</span>
              코드 붙여넣기
            </h4>
            <p className="text-sm text-muted-foreground">HTML, CSS, JS/TS, JSON, SQL, YAML, Markdown, GraphQL 코드를 붙여넣습니다.</p>
          </div>
          <div className="p-4 rounded-lg border bg-muted/20">
            <h4 className="font-bold mb-2 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs">2</span>
              패턴 분석
            </h4>
            <p className="text-sm text-muted-foreground">9개 이상의 언어를 지원하는 분석 엔진이 실시간으로 스캔을 시작합니다.</p>
          </div>
          <div className="p-4 rounded-lg border bg-muted/20">
            <h4 className="font-bold mb-2 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs">3</span>
              결과 활용
            </h4>
            <p className="text-sm text-muted-foreground">생성된 리포트를 읽거나 '리포트 복사' 기능을 통해 공유하세요.</p>
          </div>
        </div>
      </ToolSection>

      <div className="my-12 border-t pt-12" />

      <ToolSection title="코드 분석기(Code Lens) 완벽 가이드" headingLevel="h2" className="my-8">
        <div className="prose dark:prose-invert max-w-none">
          <h3>코드를 '읽는' 시대에서 '이해하는' 시대로</h3>
          <p>
            단순히 문법을 아는 것과 코드의 의도를 파악하는 것은 별개의 영역입니다. Code Lens는 개발자가 작성한 코드의 뼈대를 분석하여, 
            이 코드가 어떤 역할을 수행하고 데이터가 어떻게 흐르는지 자연어로 풀어 설명합니다.
          </p>
          
          <h4>지원 언어 및 상세 분석 범위</h4>
          <div className="overflow-x-auto my-6 border rounded-xl overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-muted">
                  <th className="p-4 border text-left">카테고리</th>
                  <th className="p-4 border text-left">언어</th>
                  <th className="p-4 border text-left">주요 분석 내용</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                <tr>
                  <td className="p-4 border font-bold bg-muted/30">프론트엔드</td>
                  <td className="p-4 border text-primary font-medium">JS, TS, React</td>
                  <td className="p-4 border text-muted-foreground">컴포넌트 구조, 상태 관리(useState), 부수 효과(useEffect), 리스트 렌더링, 비동기 통신 등</td>
                </tr>
                <tr>
                  <td className="p-4 border font-bold bg-muted/30">디자인/구조</td>
                  <td className="p-4 border text-primary font-medium">HTML, CSS, Tailwind</td>
                  <td className="p-4 border text-muted-foreground">시맨틱 태그 구조, 레이아웃(Flex/Grid), Tailwind 디자인 의도, 반응형 대응 등</td>
                </tr>
                <tr>
                  <td className="p-4 border font-bold bg-muted/30">데이터/서버</td>
                  <td className="p-4 border text-primary font-medium">SQL, GraphQL</td>
                  <td className="p-4 border text-muted-foreground">데이터베이스 조회(SELECT), 조인(JOIN), 뮤테이션(Mutation), 필드 구조 분석 등</td>
                </tr>
                <tr>
                  <td className="p-4 border font-bold bg-muted/30">설정/문서</td>
                  <td className="p-4 border text-primary font-medium">JSON, YAML, MD</td>
                  <td className="p-4 border text-muted-foreground">npm 프로젝트 설정, TypeScript 컴파일 옵션, CI/CD 워크플로우, 마크다운 문서 구조 등</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h4>왜 Code Lens를 사용해야 하나요?</h4>
          <ul>
            <li><strong>초고속 분석:</strong> 모든 연산이 브라우저 내부에서 이루어져 AI보다 수십 배 빠릅니다.</li>
            <li><strong>강력한 보안:</strong> 코드가 외부 서버로 절대 전송되지 않아 기밀 코드 분석도 안전합니다.</li>
            <li><strong>협업 효율:</strong> 복잡한 코드를 팀원에게 설명할 때 '리포트 복사' 기능을 활용해 보세요.</li>
          </ul>
        </div>
      </ToolSection>
    </ToolLayout>
  );
}